/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Banco;

import Banco.Tela_inicial;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class List extends javax.swing.JFrame {

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        operador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        funcionario = new javax.swing.JButton();
        gerente = new javax.swing.JButton();
        matricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel1.setText("Matrícula");

        operador.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        operador.setText("Listar Operador");
        operador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operadorActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        funcionario.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        funcionario.setText("Listar Funcionario");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });

        gerente.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        gerente.setText("Listar Gerente");
        gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gerente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operadorActionPerformed
      // Criando um objeto Conexao
        Conexao conexaoObjeto = new Conexao();

        // Obtendo a conexão com o banco de dados
        Connection conexao = conexaoObjeto.Conexaobanco();

        //Criando variaveis para os botóes
        int valor1 = Integer.parseInt(matricula.getText());

        //Criado o objeto da classe funcionario e inserindos as variav[esi nos atributos do obj funcionario
        Operador op = new Operador();
        op.setMatricula(valor1);

        // criando a função que irá fazer a busca no banco para poder listar com o executyQuery que é usado para consultas select
        String sql = "SELECT * FROM operador WHERE matricula = ?";
        try {
            PreparedStatement PreST = conexao.prepareStatement(sql);
            PreST.setInt(1, op.getMatricula());
            ResultSet resultSet = PreST.executeQuery();
    
    // Verifica se ecntrou algum resultado na busca
    if (resultSet.next()) {
        int matricula = resultSet.getInt("matricula");
        String nome = resultSet.getString("nome");
        String idade = resultSet.getString("idade");
        String funcao = resultSet.getString("funcao");
        
        // Exibi os dados recuperados no formato de mensagem ou informar caso não seja encontrado registros
        JOptionPane.showMessageDialog(null, "Operador encontrado: " + " Matrícula " + matricula + ", Nome " + nome + ", Idade " + idade + ", Função " + funcao);
    } else {
        JOptionPane.showMessageDialog(null, "Operador não encontrado!");
    }
} catch (Exception e) {
    // Imprimir se deu erro ou não
    JOptionPane.showMessageDialog(null, "Erro ao recuperar dados: " + e.getMessage());
}
    }//GEN-LAST:event_operadorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Ação para apagar conteu dos campos
        matricula.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_inicial ti = new Tela_inicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed

        // Criando um objeto Conexao
        Conexao conexaoObjeto = new Conexao();

        // Obtendo a conexão com o banco de dados
        Connection conexao = conexaoObjeto.Conexaobanco();

        //Criando variaveis para os botóes
        int valor1 = Integer.parseInt(matricula.getText());

        //Criado o objeto da classe funcionario e inserindos as variav[esi nos atributos do obj funcionario
        Funcionario func = new Funcionario();
        func.setMatricula(valor1);

       // criando a função que irá fazer a busca no banco para poder listar com o executyQuery que é usado para consultas select
        String sql = "SELECT * FROM funcionario WHERE matricula = ?";
        try {
            PreparedStatement PreST = conexao.prepareStatement(sql);
            PreST.setInt(1, func.getMatricula());
            ResultSet resultSet = PreST.executeQuery();
    
    // Verifica se ecntrou algum resultado na busca
    if (resultSet.next()) {
        int matricula = resultSet.getInt("matricula");
        String nome = resultSet.getString("nome");
        String idade = resultSet.getString("idade");
        
         // Exibi os dados recuperados no formato de mensagem ou informar caso não seja encontrado registros
        JOptionPane.showMessageDialog(null, "Funcionário encontrado: " + " Matrícula " + matricula + ", Nome " + nome + ", Idade " + idade);
    } else {
        JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
    }
} catch (Exception e) {
    // Imprimir se deu erro ou não
    JOptionPane.showMessageDialog(null, "Erro ao recuperar dados: " + e.getMessage());
}
    }//GEN-LAST:event_funcionarioActionPerformed

    private void gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenteActionPerformed
        // Criando um objeto Conexao
        Conexao conexaoObjeto = new Conexao();

        // Obtendo a conexão com o banco de dados
        Connection conexao = conexaoObjeto.Conexaobanco();

        //Criando variaveis para os botóes
        int valor1 = Integer.parseInt(matricula.getText());

        //Criado o objeto da classe funcionario e inserindos as variav[esi nos atributos do obj funcionario
        Gerente gen = new Gerente();
        gen.setMatricula(valor1);

        // criando a função que irá fazer a busca no banco para poder listar com o executyQuery que é usado para consultas select
        String sql = "SELECT * FROM gerente WHERE matricula = ?";
        try {
            PreparedStatement PreST = conexao.prepareStatement(sql);
            PreST.setInt(1, gen.getMatricula());
            ResultSet resultSet = PreST.executeQuery();
    
    // Verifica se ecntrou algum resultado na busca
    if (resultSet.next()) {
        int matricula = resultSet.getInt("matricula");
        String nome = resultSet.getString("nome");
        String idade = resultSet.getString("idade");
        String departamento = resultSet.getString("departamento");
        
        // Exibi os dados recuperados no formato de mensagem ou informar caso não seja encontrado registros
        JOptionPane.showMessageDialog(null, "Gerente encontrado: " + " Matrícula " + matricula + ", Nome " + nome + ", Idade " + idade + ", Departamento " + departamento);
    } else {
        JOptionPane.showMessageDialog(null, "Gerente não encontrado!");
    }
} catch (Exception e) {
    // Imprimir se deu erro ou não
    JOptionPane.showMessageDialog(null, "Erro ao recuperar dados: " + e.getMessage());
}
    }//GEN-LAST:event_gerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton funcionario;
    private javax.swing.JButton gerente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField matricula;
    private javax.swing.JButton operador;
    // End of variables declaration//GEN-END:variables

    


}
